[package]
name = "btech"
version = "0.1.0"
edition = "2024"

[dependencies]
uuid = { version = "1", features = ["v4"] }
clap = { version = "4", features = ["derive"] }
lipsum = { version = "0.9" }
regex = "1.10"
arboard = "3.6.1"

